services:
  web:
    container_name: web
    build: web
    ports:
      - '3030:3030'
    volumes:
      - ./web/:/web/
      - /web/node_modules/
  app:
    container_name: app
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./app/:/app/
      - /app/instance/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 1s

  profiler:
    container_name: app_profiler
    build:
      context: ./profiler
      dockerfile: Dockerfile
    restart: always
    cap_add:
      - SYS_PTRACE
    pid: "container:app"
    volumes:
      - ./profiler/profiles:/profiles
    depends_on:
      app:
        condition: service_healthy
